#!/usr/bin/ruby

require 'win32ole'
require 'kconv'
require 'net/smtp'
require 'vr/vruby'
require 'vr/vrcontrol'
require 'vr/contrib/inifile'

$KCODE = 'SJIS'

$HOST = ''
$FROMADDRESS = ''
$POSTADDRESS = ''
$WATCHDIR = ''

AGENT = "vnt2postimage.rb/ruby/#{RUBY_VERSION}"
DEFAULTHOST = 'localhost'

wsh = WIN32OLE.new('Wscript.Shell')


module Frm_form1

  def _form1_init
    $_form1_fonts=[
      @screen.factory.newfont('MS UI Gothic',-16,0,4,0,0,0,50,128)
    ]
    self.caption = 'vnt2PostImage 設定'
    self.move(140,124,464,224)
    label_x = 8
    edit_x = 180
    edit_w = 168
    y = 12
    addControl(VRStatic,'static1',"あなたのメールアドレス",label_x,y,176,24,1342177280)
    @static1.setFont($_form1_fonts[0])
    addControl(VREdit,'edit1',$FROMADDRESS,edit_x,y-2,edit_w,24,1342177408)
    y += 32
    addControl(VRStatic,'static2',"画像の投稿アドレス",label_x,y,176,24,1342177280)
    @static2.setFont($_form1_fonts[0])
    addControl(VREdit,'edit2',$POSTADDRESS,edit_x,y-2,edit_w,24,1342177408)
    y += 32
    addControl(VRStatic,'static4',"メールサーバ名",label_x,y,176,24,1342177280)
    @static4.setFont($_form1_fonts[0])
    addControl(VREdit,'edit4',$HOST,edit_x,y-2,edit_w,24,1342177408)
    y += 32
    addControl(VRStatic,'static3',"監視フォルダ",label_x,y,176,24,1342177280)
    @static3.setFont($_form1_fonts[0])
    addControl(VREdit,'edit3',$WATCHDIR,edit_x,y-2,edit_w,24,1342177408)
    y += 45
    addControl(VRButton,'button1',"OK",93,y,80,24,1342177280)
    addControl(VRButton,'button2',"Cancel",266,y,80,24,1342177280)
  end

  def button1_clicked
    $ini.write("vnt2postimage", "HOST", @edit4.text)
    $ini.write("vnt2postimage", "FROMADDRESS", @edit1.text)
    $ini.write("vnt2postimage", "POSTADDRESS", @edit2.text)
    $ini.write("vnt2postimage", "WATCHDIR", @edit3.text)
    $ini.flash()
    close
  end

  def button2_clicked
    close
  end

  def construct
    _form1_init
  end

end


def postImage(subject, image, filename, ext)
  body = ""
  body.concat("To: #{$POSTADDRESS}\r\n")
  body.concat("Subject: ")
  body.concat(subject)
  body.concat("\r\n")
  body.concat("MIME-Version: 1.0 (generated by #{AGENT}\r\n")
  body.concat("Content-Type: image/#{ext}\r\n")
  body.concat("Content-Disposition: inline; filename=\"#{filename}\"\r\n")
  body.concat("Content-Transfer-Encoding: base64\r\n")
  body.concat("\r\n")
  body.concat(image)
  body.concat("\r\n")

  Net::SMTP.start($HOST, 25) {|smtp|
    smtp.send_mail body, $FROMADDRESS, $POSTADDRESS
  }
end #end of def

def decodeVNT(filename)
  isBody = false;
  orgExt = orgFilename = image = ""
  open(filename) {|f|
    line = f.read
    if (isBody)
	  image += line
  	else
  	  if (line =~ /^X-DOCOMO-TYPE:(.+)$/)
  	  	orgExt = $1
  	  elsif (line =~ /^X-DOCOMO-FILENAME:(.+)$/)
  	  	orgFilename = $1
  	  elsif (line =~ /^X-DOCOMO-BODY;ENCODING=BASE64:/)
  	  	body = ""
  	  	isBody = true
  	  elsif (line.length == 0|| line =~ /^END:VNOTE/)
  	  	isBody = false
  	  end
	end
  }
  postImage(orgFilename, image, orgFilename, orgExt)
end

CSIDL_LOCAL_APPDATA = 0x001c

max_pathlen = 260
windir = ' '*(max_pathlen+1)
begin
  getdir = Win32API.new('shell32', 'SHGetFolderPath', 'LLLLP', 'L')
  raise RuntimeError if getdir.call(0, CSIDL_LOCAL_APPDATA, 0, 0, windir) != 0
  windir = File.expand_path(windir.rstrip.chop)
rescue
  wsh.Popup('設定ファイルのあるディレクトリが見つかりません。代わりのディレクトリを使用します。')
  windir = "."
end
conf_file = "#{windir}/vnt2postimage.cnf"
$ini = Inifile.new(conf_file)
$HOST = $ini.read("vnt2postimage", "HOST")
$FROMADDRESS = $ini.read("vnt2postimage", "FROMADDRESS")
$POSTADDRESS = $ini.read("vnt2postimage", "POSTADDRESS")
$WATCHDIR = $ini.read("vnt2postimage", "WATCHDIR")

if $HOST.nil? || $HOST == ''
  $HOST = DEFAULTHOST
end

if $FROMADDRESS.nil? || $FROMADDRESS == '' ||
  $POSTADDRESS.nil? || $POSTADDRESS == '' || $WATCHDIR.nil? || $WATCHDIR == '' ||
  ARGV[0] =~ /[-\/]s/
    VRLocalScreen.start Frm_form1
    exit
end

Dir.glob($WATCHDIR + "/*.vnt") {|f|
  if (decodeVNT(f))
  	File.unlink(f)
  end
}
